# Generated by Django 5.1.5 on 2025-01-26 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='class_room',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('room_no', models.CharField(max_length=5, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='courses',
            fields=[
                ('course_id', models.CharField(max_length=7, primary_key=True, serialize=False, unique=True)),
                ('course_name', models.CharField(max_length=30, unique=True)),
                ('credit', models.IntegerField()),
                ('dept', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='course_in_department', to='auth_api.department')),
            ],
        ),
    ]
