# Generated by Django 5.1.5 on 2025-01-27 15:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0003_alter_class_room_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class_room',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False, unique=True),
        ),
    ]
