# Generated by Django 5.1.5 on 2025-01-29 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_api', '0004_alter_class_room_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.CharField(default='fabcb71c9f934dd2bebd5e123eb7b0f5', max_length=36, primary_key=True, serialize=False, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('room_no', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth_api.class_room')),
            ],
        ),
    ]
