# Generated by Django 5.1.5 on 2025-01-30 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='id',
            field=models.CharField(default='b15db545b01b41d1b1779edc99aae600', max_length=36, primary_key=True, serialize=False, unique=True),
        ),
    ]
