# Generated by Django 5.1.5 on 2025-01-30 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_api', '0002_alter_client_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='id',
            field=models.CharField(default='1e6af36b20784e5aa0e82b94b45c6a37', max_length=36, primary_key=True, serialize=False, unique=True),
        ),
    ]
