# Generated by Django 5.1.5 on 2025-02-02 10:13

import backend.services
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_api', '0004_alter_client_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='id',
            field=models.CharField(default=backend.services.uniqueid.generateid, max_length=36, primary_key=True, serialize=False, unique=True),
        ),
    ]
