# Generated by Django 5.1.5 on 2025-01-27 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_api', '0002_class_room_courses'),
        ('users', '0006_alter_customuser_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='class_slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth_api.courses')),
                ('faculty', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.faculty')),
                ('room_no', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth_api.class_room')),
            ],
        ),
        migrations.CreateModel(
            name='attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_id', models.ManyToManyField(to='users.student')),
                ('slot', models.ManyToManyField(to='attendance_api.class_slot')),
            ],
        ),
    ]
