# Generated by Django 5.1.5 on 2025-01-27 04:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class_slot',
            name='starttime',
            field=models.TimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='class_slot',
            name='token',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='class_slot',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
