# Generated by Django 5.1.5 on 2025-01-27 13:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_api', '0002_class_slot_starttime_class_slot_token_and_more'),
        ('auth_api', '0003_alter_class_room_id'),
        ('users', '0006_alter_customuser_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class_slot',
            name='course',
        ),
        migrations.RemoveField(
            model_name='class_slot',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='class_slot',
            name='room_no',
        ),
        migrations.CreateModel(
            name='section',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('section', models.CharField(max_length=5)),
                ('department', models.ManyToManyField(to='auth_api.department')),
                ('mentor', models.ManyToManyField(to='users.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='student_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.ManyToManyField(to='attendance_api.section')),
                ('student', models.ManyToManyField(to='users.student')),
            ],
        ),
        migrations.AddField(
            model_name='class_slot',
            name='course',
            field=models.ManyToManyField(to='auth_api.courses'),
        ),
        migrations.AddField(
            model_name='class_slot',
            name='faculty',
            field=models.ManyToManyField(to='users.faculty'),
        ),
        migrations.AddField(
            model_name='class_slot',
            name='room_no',
            field=models.ManyToManyField(to='auth_api.class_room'),
        ),
    ]
