# Generated by Django 5.1.5 on 2025-01-27 13:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_api', '0003_remove_class_slot_course_remove_class_slot_faculty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class_slot',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='class_slot',
            name='token',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
