# Generated by Django 5.1.5 on 2025-01-27 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_api', '0004_alter_class_slot_id_alter_class_slot_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='class_slot',
            name='section',
            field=models.ManyToManyField(to='attendance_api.section'),
        ),
    ]
