# Generated by Django 5.1.5 on 2025-01-27 14:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_api', '0005_class_slot_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class_slot',
            name='starttime',
        ),
        migrations.AddField(
            model_name='class_slot',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 1, 27, 14, 13, 42, 665488, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
