# Generated by Django 5.1.5 on 2025-01-27 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_api', '0006_remove_class_slot_starttime_class_slot_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='enrollment_id',
            new_name='student',
        ),
    ]
