# Generated by Django 5.1.5 on 2025-01-29 04:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_api', '0009_alter_section_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class_slot',
            name='id',
            field=models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='id',
            field=models.CharField(default='5139a27b1cc04d208bba2e94c6721ba9', max_length=36, primary_key=True, serialize=False, unique=True),
        ),
    ]
