# Generated by Django 5.1.5 on 2025-01-29 04:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_api', '0010_alter_class_slot_id_alter_section_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class_slot',
            name='id',
            field=models.CharField(default='fea419ee94a24720a49deea95701dfba', max_length=36, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='id',
            field=models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False, unique=True),
        ),
    ]
