# Generated by Django 5.1.5 on 2025-01-29 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_api', '0011_alter_class_slot_id_alter_section_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class_slot',
            name='id',
            field=models.CharField(default='c7d158bc62564415bb5b2c9b4dad2f56', max_length=36, primary_key=True, serialize=False, unique=True),
        ),
    ]
