# Generated by Django 5.1.5 on 2025-01-29 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_api', '0012_alter_class_slot_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class_slot',
            name='id',
            field=models.CharField(default='b95eb53e3398446cba8df087e0ddaa1b', max_length=36, primary_key=True, serialize=False, unique=True),
        ),
    ]
