# Generated by Django 5.1.5 on 2025-01-29 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_api', '0014_alter_class_slot_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class_slot',
            name='id',
            field=models.CharField(default='298e23ed18c8408cb9137e3cfb23853a', max_length=36, primary_key=True, serialize=False, unique=True),
        ),
    ]
