# Generated by Django 5.1.5 on 2025-01-29 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_api', '0015_alter_class_slot_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class_slot',
            name='id',
            field=models.CharField(default='2f483482588b498d86e118011bfca598', max_length=36, primary_key=True, serialize=False, unique=True),
        ),
    ]
