# Generated by Django 5.1.5 on 2025-01-30 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_api', '0016_alter_class_slot_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class_slot',
            name='id',
            field=models.CharField(default='<function uuid4 at 0x0000025C41B59C60>', max_length=36, primary_key=True, serialize=False, unique=True),
        ),
    ]
