# Generated by Django 5.1.5 on 2025-01-30 11:16

import backend.services
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_api', '0017_alter_class_slot_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class_slot',
            name='id',
            field=models.CharField(default=backend.services.uniqueid.generateid, editable=False, max_length=36, primary_key=True, serialize=False, unique=True),
        ),
    ]
