# Generated by Django 5.1.5 on 2025-01-30 13:20

import backend.services
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_api', '0018_alter_class_slot_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='id',
            field=models.CharField(default=backend.services.uniqueid.generateid, max_length=36, primary_key=True, serialize=False, unique=True),
        ),
    ]
