# Generated by Django 5.1.5 on 2025-02-02 10:13

import backend.services
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_api', '0019_alter_section_id'),
        ('client_api', '0005_alter_client_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='class_slot',
            name='client',
            field=models.ManyToManyField(to='client_api.client'),
        ),
        migrations.AlterField(
            model_name='class_slot',
            name='id',
            field=models.CharField(default=backend.services.uniqueid.generateid, max_length=36, primary_key=True, serialize=False, unique=True),
        ),
    ]
