# Generated by Django 5.1.5 on 2025-01-26 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0001_initial'),
        ('users', '0003_remove_student_sem_student_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth_api.department'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='faculty_id',
            field=models.CharField(default='1nh23fac01', max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
