# Generated by Django 5.1.5 on 2025-01-26 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_faculty_department_faculty_faculty_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='id',
        ),
    ]
